# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# -----------------------------------------------------------------------------
# Generated by Merlin Studio v2 (architex-v2) — OpenTofu backend.tf — remote state in S3 + DynamoDB locking
# Organization: AcmeCorp
# Profile:      STANDARD
# Generated:    2026-08-04T14:55:24.584722Z
# Wizard:       v1.0.0
# -----------------------------------------------------------------------------
# Scaffolding — not a finished artifact. Merlin renders this from your
# declared intent (profile, frameworks, accounts, topology). Adapt it to
# your environment: tighten CIDRs, refine policy bodies, add team tags,
# pin module versions, layer account-specific overrides. Re-run the wizard
# when *intent* shifts; keep day-to-day customisation in your IaC fork
# (regen overwrites this directory).
# Replace PLACEHOLDER_ tokens with real values from your AWS Organization
# before `tofu apply` / `cdk deploy` / LZA pipeline run — see PLACEHOLDERS.md.

# Remote state bucket lives in the management account; lock table in DynamoDB.
# Bootstrap EVERYTHING this block references OUT-OF-BAND before first
# `tofu init` — including the state KMS key + alias. The backend must never
# depend on a resource this stack creates (chicken-and-egg: `tofu init` needs
# the key before the stack that would create it can apply). One-time bootstrap:
#
#   aws kms create-key --description "acmecorp OpenTofu state" \
#     --query KeyMetadata.KeyId --output text --region us-east-1
#   aws kms create-alias --alias-name alias/acmecorp-tofu-state \
#     --target-key-id <key-id-from-previous-step> --region us-east-1
#   aws s3api create-bucket --bucket acmecorp-tofu-state --region us-east-1
#   aws s3api put-bucket-versioning --bucket acmecorp-tofu-state \
#     --versioning-configuration Status=Enabled
#   aws s3api put-bucket-encryption --bucket acmecorp-tofu-state \
#     --server-side-encryption-configuration '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"aws:kms","KMSMasterKeyID":"alias/acmecorp-tofu-state"},"BucketKeyEnabled":true}]}'
#   aws dynamodb create-table --table-name acmecorp-tofu-state-lock \
#     --attribute-definitions AttributeName=LockID,AttributeType=S \
#     --key-schema AttributeName=LockID,KeyType=HASH \
#     --billing-mode PAY_PER_REQUEST --region us-east-1

terraform {
  backend "s3" {
    bucket         = "acmecorp-tofu-state"
    key            = "aws-landing-zone/terraform.tfstate"
    region         = "us-east-1"
    encrypt        = true
    kms_key_id     = "alias/acmecorp-tofu-state"
    dynamodb_table = "acmecorp-tofu-state-lock"
  }
}