# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# -----------------------------------------------------------------------------
# Generated by Merlin Studio v2 (architex-v2) — OpenTofu backup.tf — AWS Backup vault + plan
# Organization: AcmeCorp
# Profile:      STANDARD
# Generated:    2026-08-04T14:55:24.584722Z
# Wizard:       v1.0.0
# -----------------------------------------------------------------------------
# Scaffolding — not a finished artifact. Merlin renders this from your
# declared intent (profile, frameworks, accounts, topology). Adapt it to
# your environment: tighten CIDRs, refine policy bodies, add team tags,
# pin module versions, layer account-specific overrides. Re-run the wizard
# when *intent* shifts; keep day-to-day customisation in your IaC fork
# (regen overwrites this directory).
# Replace PLACEHOLDER_ tokens with real values from your AWS Organization
# before `tofu apply` / `cdk deploy` / LZA pipeline run — see PLACEHOLDERS.md.

resource "aws_backup_vault" "central" {
  name          = "central-vault"
  kms_key_arn   = aws_kms_key.accelerator.arn
  force_destroy = false

  tags = local.default_tags
}


resource "aws_backup_vault_lock_configuration" "central" {
  backup_vault_name   = aws_backup_vault.central.name
  changeable_for_days = 3
  max_retention_days  = 2555
  min_retention_days  = 365
}

resource "aws_iam_role" "backup" {
  name = "AWSBackupServiceRole"

  assume_role_policy = jsonencode({
    Version   = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "backup.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })
}

resource "aws_iam_role_policy_attachment" "backup_managed" {
  role       = aws_iam_role.backup.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForBackup"
}

resource "aws_iam_role_policy_attachment" "backup_restore_managed" {
  role       = aws_iam_role.backup.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForRestores"
}

# Default daily backup plan
resource "aws_backup_plan" "daily" {
  name = "acmecorp-daily"

  rule {
    rule_name         = "DailyAtMidnightUTC"
    target_vault_name = aws_backup_vault.central.name
    schedule          = "cron(0 5 ? * * *)"
    start_window      = 60
    completion_window = 180

    lifecycle {
      cold_storage_after = 90
      delete_after       = 365
    }

    recovery_point_tags = local.default_tags
  }

  tags = local.default_tags
}

data "aws_caller_identity" "current" {}

resource "aws_backup_selection" "daily" {
  iam_role_arn = aws_iam_role.backup.arn
  name         = "daily-tagged"
  plan_id      = aws_backup_plan.daily.id

  selection_tag {
    type  = "STRINGEQUALS"
    key   = "Backup"
    value = "true"
  }
}

# Organization-wide backup policy
