# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# -----------------------------------------------------------------------------
# Generated by Merlin Studio v2 (architex-v2) — OpenTofu cloudtrail.tf — organization trail + S3 destination
# Organization: AcmeCorp
# Profile:      STANDARD
# Generated:    2026-08-04T14:55:24.584722Z
# Wizard:       v1.0.0
# -----------------------------------------------------------------------------
# Scaffolding — not a finished artifact. Merlin renders this from your
# declared intent (profile, frameworks, accounts, topology). Adapt it to
# your environment: tighten CIDRs, refine policy bodies, add team tags,
# pin module versions, layer account-specific overrides. Re-run the wizard
# when *intent* shifts; keep day-to-day customisation in your IaC fork
# (regen overwrites this directory).
# Replace PLACEHOLDER_ tokens with real values from your AWS Organization
# before `tofu apply` / `cdk deploy` / LZA pipeline run — see PLACEHOLDERS.md.

resource "aws_cloudwatch_log_group" "cloudtrail" {
  provider          = aws.log_archive
  name              = "/aws/cloudtrail/acmecorp-org-trail"
  # CloudWatch only accepts a fixed set of retention values; cw_retention snaps a
  # compliance floor (e.g. 7y = 2555) up to the nearest valid value (2557).
  retention_in_days = 365
  kms_key_id        = aws_kms_alias.central_logs.target_key_arn
}

resource "aws_iam_role" "cloudtrail_to_cw" {
  provider = aws.log_archive
  name     = "CloudTrailToCloudWatch"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "cloudtrail.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })
}

resource "aws_iam_role_policy" "cloudtrail_to_cw" {
  provider = aws.log_archive
  name     = "CloudTrailToCloudWatch"
  role     = aws_iam_role.cloudtrail_to_cw.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Action = [
        "logs:CreateLogStream",
        "logs:PutLogEvents",
      ]
      Resource = "${aws_cloudwatch_log_group.cloudtrail.arn}:*"
    }]
  })
}

# Notification topic for the org trail (CKV_AWS_252). Subscribers (PagerDuty,
# SOC SIEM, e-mail) attach to this topic to fan out per-event delivery beyond
# the centralized S3 archive. KMS-encrypted with the central-logs CMK so the
# topic body stays consistent with the trail data it announces.
resource "aws_sns_topic" "cloudtrail" {
  provider          = aws.log_archive
  name              = "acmecorp-org-trail-notifications"
  kms_master_key_id = aws_kms_key.central_logs.id
  tags              = local.default_tags
}

# Allow cloudtrail.amazonaws.com to publish into the topic.
data "aws_iam_policy_document" "cloudtrail_sns" {
  provider = aws.log_archive
  statement {
    sid     = "AWSCloudTrailSNSPolicy"
    effect  = "Allow"
    actions = ["SNS:Publish"]
    principals {
      type        = "Service"
      identifiers = ["cloudtrail.amazonaws.com"]
    }
    resources = [aws_sns_topic.cloudtrail.arn]
  }
}

resource "aws_sns_topic_policy" "cloudtrail" {
  provider = aws.log_archive
  arn      = aws_sns_topic.cloudtrail.arn
  policy   = data.aws_iam_policy_document.cloudtrail_sns.json
}

resource "aws_cloudtrail" "org" {
  provider                      = aws.log_archive
  name                          = "acmecorp-org-trail"
  is_organization_trail         = true
  is_multi_region_trail         = true
  include_global_service_events = true
  enable_log_file_validation    = true
  enable_logging                = true

  s3_bucket_name = aws_s3_bucket.central_logs.id
  s3_key_prefix  = "cloudtrail"

  # SNS fanout for per-event delivery (CKV_AWS_252). Topic body + policy above.
  sns_topic_name = aws_sns_topic.cloudtrail.arn

  cloud_watch_logs_group_arn = "${aws_cloudwatch_log_group.cloudtrail.arn}:*"
  cloud_watch_logs_role_arn  = aws_iam_role.cloudtrail_to_cw.arn

  kms_key_id = aws_kms_alias.central_logs.target_key_arn

  # Feature flags from generators/aws_cloudtrail_features.py.
  event_selector {
    read_write_type           = "All"
    include_management_events = true
    data_resource {
      type   = "AWS::S3::Object"
      values = ["arn:aws:s3"]
    }
  }

  insight_selector { insight_type = "ApiErrorRateInsight" }

  depends_on = [
    aws_s3_bucket_policy.central_logs_cloudtrail,
  ]
}