# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# -----------------------------------------------------------------------------
# Generated by Merlin Studio v2 (architex-v2) — OpenTofu config.tf — AWS Config recorder + aggregator + rules
# Organization: AcmeCorp
# Profile:      STANDARD
# Generated:    2026-08-04T14:55:24.584722Z
# Wizard:       v1.0.0
# -----------------------------------------------------------------------------
# Scaffolding — not a finished artifact. Merlin renders this from your
# declared intent (profile, frameworks, accounts, topology). Adapt it to
# your environment: tighten CIDRs, refine policy bodies, add team tags,
# pin module versions, layer account-specific overrides. Re-run the wizard
# when *intent* shifts; keep day-to-day customisation in your IaC fork
# (regen overwrites this directory).
# Replace PLACEHOLDER_ tokens with real values from your AWS Organization
# before `tofu apply` / `cdk deploy` / LZA pipeline run — see PLACEHOLDERS.md.
# Compliance frameworks declared on this spec:
#   - cis
#   - pci_dss
#   - iso27001
#   - soc2

# Delegate AWS Config administration to the Audit account
resource "aws_organizations_delegated_administrator" "config" {
  account_id        = "PLACEHOLDER_ACCOUNT_ID_Audit"
  service_principal = "config.amazonaws.com"
}

resource "aws_organizations_delegated_administrator" "config_multiaccountsetup" {
  account_id        = "PLACEHOLDER_ACCOUNT_ID_Audit"
  service_principal = "config-multiaccountsetup.amazonaws.com"
}

# IAM role used by the Config recorder
resource "aws_iam_role" "config" {
  provider = aws.audit
  name     = "AWSConfigRole-Org"

  assume_role_policy = jsonencode({
    Version   = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "config.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })
}

resource "aws_iam_role_policy_attachment" "config_managed" {
  provider   = aws.audit
  role       = aws_iam_role.config.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWS_ConfigRole"
}

resource "aws_config_configuration_recorder" "this" {
  provider = aws.audit
  name     = "default"
  role_arn = aws_iam_role.config.arn

  recording_group {
    all_supported                 = true
    include_global_resource_types = true
  }
}

resource "aws_config_delivery_channel" "this" {
  provider       = aws.audit
  name           = "default"
  s3_bucket_name = aws_s3_bucket.central_logs.id
  s3_key_prefix  = "config"
  s3_kms_key_arn = aws_kms_alias.central_logs.target_key_arn

  snapshot_delivery_properties {
    delivery_frequency = "TwentyFour_Hours"
  }

  depends_on = [aws_config_configuration_recorder.this]
}

resource "aws_config_configuration_recorder_status" "this" {
  provider   = aws.audit
  name       = aws_config_configuration_recorder.this.name
  is_enabled = true
  depends_on = [aws_config_delivery_channel.this]
}

# Organization-wide aggregator
resource "aws_config_configuration_aggregator" "org" {
  provider = aws.audit
  name     = "org-aggregator"

  organization_aggregation_source {
    all_regions = true
    role_arn    = aws_iam_role.config_aggregator.arn
  }
}

resource "aws_iam_role" "config_aggregator" {
  provider = aws.audit
  name     = "AWSConfigRoleForOrganizations-Aggregator"

  assume_role_policy = jsonencode({
    Version   = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "config.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })
}

resource "aws_iam_role_policy_attachment" "config_aggregator_managed" {
  provider   = aws.audit
  role       = aws_iam_role.config_aggregator.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSConfigRoleForOrganizations"
}

# Managed Config rules driven by compliance frameworks
resource "aws_config_organization_managed_rule" "encrypted_volumes" {
  provider        = aws.audit
  name            = "encrypted-volumes"
  rule_identifier = "ENCRYPTED_VOLUMES"
  depends_on      = [aws_organizations_delegated_administrator.config]
}
resource "aws_config_organization_managed_rule" "rds_storage_encrypted" {
  provider        = aws.audit
  name            = "rds-storage-encrypted"
  rule_identifier = "RDS_STORAGE_ENCRYPTED"
  depends_on      = [aws_organizations_delegated_administrator.config]
}
resource "aws_config_organization_managed_rule" "s3_bucket_server_side_encryption_enabled" {
  provider        = aws.audit
  name            = "s3-bucket-server-side-encryption-enabled"
  rule_identifier = "S3_BUCKET_SERVER_SIDE_ENCRYPTION_ENABLED"
  depends_on      = [aws_organizations_delegated_administrator.config]
}
resource "aws_config_organization_managed_rule" "cloud_trail_enabled" {
  provider        = aws.audit
  name            = "cloud-trail-enabled"
  rule_identifier = "CLOUD_TRAIL_ENABLED"
  depends_on      = [aws_organizations_delegated_administrator.config]
}
resource "aws_config_organization_managed_rule" "cloud_trail_encryption_enabled" {
  provider        = aws.audit
  name            = "cloud-trail-encryption-enabled"
  rule_identifier = "CLOUD_TRAIL_ENCRYPTION_ENABLED"
  depends_on      = [aws_organizations_delegated_administrator.config]
}
resource "aws_config_organization_managed_rule" "iam_password_policy" {
  provider        = aws.audit
  name            = "iam-password-policy"
  rule_identifier = "IAM_PASSWORD_POLICY"
  depends_on      = [aws_organizations_delegated_administrator.config]
}
resource "aws_config_organization_managed_rule" "vpc_flow_logs_enabled" {
  provider        = aws.audit
  name            = "vpc-flow-logs-enabled"
  rule_identifier = "VPC_FLOW_LOGS_ENABLED"
  depends_on      = [aws_organizations_delegated_administrator.config]
}
