# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# -----------------------------------------------------------------------------
# Generated by Merlin Studio v2 (architex-v2) — OpenTofu iam.tf — IAM Identity Center + workload roles
# Organization: AcmeCorp
# Profile:      STANDARD
# Generated:    2026-08-04T14:55:24.584722Z
# Wizard:       v1.0.0
# -----------------------------------------------------------------------------
# Scaffolding — not a finished artifact. Merlin renders this from your
# declared intent (profile, frameworks, accounts, topology). Adapt it to
# your environment: tighten CIDRs, refine policy bodies, add team tags,
# pin module versions, layer account-specific overrides. Re-run the wizard
# when *intent* shifts; keep day-to-day customisation in your IaC fork
# (regen overwrites this directory).
# Replace PLACEHOLDER_ tokens with real values from your AWS Organization
# before `tofu apply` / `cdk deploy` / LZA pipeline run — see PLACEHOLDERS.md.

# Look up the IAM Identity Center instance (must be enabled in the org).
data "aws_ssoadmin_instances" "this" {}

locals {
  sso_instance_arn   = data.aws_ssoadmin_instances.this.arns[0]
  identity_store_id  = data.aws_ssoadmin_instances.this.identity_store_ids[0]
}

# Permission sets
resource "aws_ssoadmin_permission_set" "admin" {
  name             = "AdministratorAccess"
  description      = "Full administrative access. Restrict via SCP."
  instance_arn     = local.sso_instance_arn
  session_duration = "PT1H"
}

# The Identity Center "AdministratorAccess" permission set is the canonical
# admin entry-point and is itself constrained by org-level SCPs
# (Deny-Root-Access, Region-Restriction, Protect-Security-Services). Removing
# AdministratorAccess from this permission set would break the cloud admin
# workflow; defense-in-depth lives at the SCP layer. See SECURITY_SCORECARD.md
# "Suppressed Checks" for the full rationale.
resource "aws_ssoadmin_managed_policy_attachment" "admin_aws_managed" {
  # checkov:skip=CKV_AWS_274: Identity Center Cloud-Administrators role; defense-in-depth via org SCPs
  instance_arn       = local.sso_instance_arn
  managed_policy_arn = "arn:aws:iam::aws:policy/AdministratorAccess"
  permission_set_arn = aws_ssoadmin_permission_set.admin.arn
}

resource "aws_ssoadmin_permission_set" "power_user" {
  name             = "PowerUserAccess"
  description      = "Power user access (no IAM/Org/Billing)."
  instance_arn     = local.sso_instance_arn
  session_duration = "PT8H"
}

resource "aws_ssoadmin_managed_policy_attachment" "power_user" {
  instance_arn       = local.sso_instance_arn
  managed_policy_arn = "arn:aws:iam::aws:policy/PowerUserAccess"
  permission_set_arn = aws_ssoadmin_permission_set.power_user.arn
}

resource "aws_ssoadmin_permission_set" "read_only" {
  name             = "ReadOnlyAccess"
  description      = "Read-only across services."
  instance_arn     = local.sso_instance_arn
  session_duration = "PT8H"
}

resource "aws_ssoadmin_managed_policy_attachment" "read_only" {
  instance_arn       = local.sso_instance_arn
  managed_policy_arn = "arn:aws:iam::aws:policy/ReadOnlyAccess"
  permission_set_arn = aws_ssoadmin_permission_set.read_only.arn
}

resource "aws_ssoadmin_permission_set" "billing" {
  name             = "BillingAccess"
  description      = "Read-only billing + cost explorer."
  instance_arn     = local.sso_instance_arn
  session_duration = "PT4H"
}

resource "aws_ssoadmin_managed_policy_attachment" "billing" {
  instance_arn       = local.sso_instance_arn
  managed_policy_arn = "arn:aws:iam::aws:policy/job-function/Billing"
  permission_set_arn = aws_ssoadmin_permission_set.billing.arn
}

resource "aws_ssoadmin_permission_set" "security_audit" {
  name             = "SecurityAuditAccess"
  description      = "SecurityAudit + ReadOnly."
  instance_arn     = local.sso_instance_arn
  session_duration = "PT8H"
}

resource "aws_ssoadmin_managed_policy_attachment" "security_audit_securityaudit" {
  instance_arn       = local.sso_instance_arn
  managed_policy_arn = "arn:aws:iam::aws:policy/SecurityAudit"
  permission_set_arn = aws_ssoadmin_permission_set.security_audit.arn
}

resource "aws_ssoadmin_managed_policy_attachment" "security_audit_readonly" {
  instance_arn       = local.sso_instance_arn
  managed_policy_arn = "arn:aws:iam::aws:policy/ReadOnlyAccess"
  permission_set_arn = aws_ssoadmin_permission_set.security_audit.arn
}

# LZ-level IAM roles — sourced from generators/aws_lz_iam_roles.py so
# every format ships the same role set.
resource "aws_iam_role" "breakglassrole" {
  name        = "BreakGlassRole"
  description = "Emergency administrative access. Use only when IAM Identity Center is unavailable."
  max_session_duration = 3600
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { AWS = "arn:aws:iam::PLACEHOLDER_ACCOUNT_ID_Management:root" }
      Action    = "sts:AssumeRole"
    }]
  })
}
# BreakGlassRole is the break-glass identity used only when Identity Center
# is unavailable. AdministratorAccess is required for that workflow; SCPs
# and CloudTrail alerting on AssumeRole calls into this role are the
# defense-in-depth. See SECURITY_SCORECARD.md "Suppressed Checks".
resource "aws_iam_role_policy_attachment" "breakglassrole_administratoraccess" {
  # checkov:skip=CKV_AWS_274: Break-glass emergency role; SCPs + CloudTrail alerts are the defense-in-depth
  role       = aws_iam_role.breakglassrole.name
  policy_arn = "arn:aws:iam::aws:policy/AdministratorAccess"
}

# Optional: OIDC providers (GitHub Actions, etc.)
resource "aws_iam_openid_connect_provider" "githubactions" {
  url             = "https://token.actions.githubusercontent.com"
  client_id_list  = ["sts.amazonaws.com"]
  thumbprint_list = []
}

# Workload roles (section 03) — e.g. the CI / Spacelift apply identity. Each is
# assumable by the declared OIDC providers (web-identity federation); if none are
# declared the trust is a placeholder you must scope to your CI principal.
resource "aws_iam_role" "wl_terraformexecutor" {
  name                 = "TerraformExecutor"
  description          = "Used by Spacelift / CI to apply Terraform"
  max_session_duration = 3600
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect    = "Allow"
        Principal = { Federated = aws_iam_openid_connect_provider.githubactions.arn }
        Action    = "sts:AssumeRoleWithWebIdentity"
        Condition = {
          StringEquals = { "token.actions.githubusercontent.com:aud" = ["sts.amazonaws.com"] }
          StringLike   = { "token.actions.githubusercontent.com:sub" = "repo:PLACEHOLDER_GIT_ORG/PLACEHOLDER_GIT_REPO:*" }
        }
      }
    ]
  })
  tags = local.default_tags
}
# TerraformExecutor carries AdministratorAccess (CI apply identity). Scope the trust
# to your CI principal and alert on AssumeRole via CloudTrail as defense-in-depth.
resource "aws_iam_role_policy_attachment" "wl_terraformexecutor_administratoraccess" {
  # checkov:skip=CKV_AWS_274: CI apply role; trust scoped to OIDC + CloudTrail alerting are the defense-in-depth
  role       = aws_iam_role.wl_terraformexecutor.name
  policy_arn = "arn:aws:iam::aws:policy/AdministratorAccess"
}
