# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# -----------------------------------------------------------------------------
# Generated by Merlin Studio v2 (architex-v2) — OpenTofu kms.tf — customer-managed KMS keys
# Organization: AcmeCorp
# Profile:      STANDARD
# Generated:    2026-08-04T14:55:24.584722Z
# Wizard:       v1.0.0
# -----------------------------------------------------------------------------
# Scaffolding — not a finished artifact. Merlin renders this from your
# declared intent (profile, frameworks, accounts, topology). Adapt it to
# your environment: tighten CIDRs, refine policy bodies, add team tags,
# pin module versions, layer account-specific overrides. Re-run the wizard
# when *intent* shifts; keep day-to-day customisation in your IaC fork
# (regen overwrites this directory).
# Replace PLACEHOLDER_ tokens with real values from your AWS Organization
# before `tofu apply` / `cdk deploy` / LZA pipeline run — see PLACEHOLDERS.md.
# Compliance frameworks declared on this spec:
#   - cis
#   - pci_dss
#   - iso27001
#   - soc2


# Account context — used by every KMS key policy below to scope the EnableRoot
# statement to the deploying account, and by the CloudWatch Logs grant to
# constrain the encryption context to log groups owned by this account
# (confused-deputy guard).
data "aws_caller_identity" "kms_account" {}

# Default key policy for the accelerator + workload CMKs (CKV2_AWS_64). Grants
# the account root full KMS administration, and grants logs.amazonaws.com use
# of the key — but only for log groups owned by this same account, which keeps
# the key from being usable by other accounts' CloudWatch Logs (confused-deputy
# protection). The central-logs key has its own broader policy (see below).
data "aws_iam_policy_document" "kms_default" {
  # The EnableRoot statement is the AWS-prescribed pattern from the KMS docs:
  # the account root must hold kms:* on resource "*" or the key becomes
  # unmanageable (AWS cannot otherwise update key administrators). The
  # principal is the account root ARN — not a wildcard — so the blast radius
  # is bounded by the deploying account itself, which already owns the key.
  # These checks fire on the wildcards alone; the constrained principal is
  # the architectural mitigation. See SECURITY_SCORECARD.md "Suppressed
  # Checks" for the full audit-trail rationale.
  # checkov:skip=CKV_AWS_109: EnableRoot requires kms:* on the account root for KMS to remain manageable (AWS-prescribed pattern)
  # checkov:skip=CKV_AWS_111: same — kms:Update*/Schedule* on root principal is the documented baseline; principal scope is the mitigation
  # checkov:skip=CKV_AWS_356: Resource="*" is required at the key-policy layer; principal scoping bounds the blast radius
  statement {
    sid    = "EnableRoot"
    effect = "Allow"
    principals {
      type        = "AWS"
      identifiers = ["arn:aws:iam::${data.aws_caller_identity.kms_account.account_id}:root"]
    }
    actions   = ["kms:*"]
    resources = ["*"]
  }

  statement {
    sid    = "AllowCloudWatchLogs"
    effect = "Allow"
    principals {
      type        = "Service"
      identifiers = ["logs.amazonaws.com"]
    }
    actions = [
      "kms:Encrypt", "kms:Decrypt", "kms:ReEncrypt*",
      "kms:GenerateDataKey*", "kms:DescribeKey",
    ]
    resources = ["*"]
    condition {
      test     = "ArnLike"
      variable = "kms:EncryptionContext:aws:logs:arn"
      values   = ["arn:aws:logs:*:${data.aws_caller_identity.kms_account.account_id}:log-group:*"]
    }
  }
}

# Accelerator key (used for accelerator-managed resources)
resource "aws_kms_key" "accelerator" {
  description              = "Default AWS LZA-managed CMK"
  customer_master_key_spec = "SYMMETRIC_DEFAULT"
  key_usage                = "ENCRYPT_DECRYPT"
  enable_key_rotation      = true
  rotation_period_in_days  = 90
  deletion_window_in_days  = 30
  is_enabled               = true
  multi_region             = false

  # Explicit key policy (CKV2_AWS_64). Default-managed policy is opaque and
  # can't be reviewed by Checkov; an explicit document is auditable.
  policy = data.aws_iam_policy_document.kms_default.json

  tags = merge(local.default_tags, { Name = "accelerator-key" })
}

resource "aws_kms_alias" "accelerator" {
  name          = "alias/acmecorp/org-key"
  target_key_id = aws_kms_key.accelerator.key_id
}

# Central-logs key policy — shared by the primary key and (when the log
# archive bucket is replicated) its DR-region replica, so both regions grant
# the same service principals + confused-deputy conditions.
# Service-principal list sourced from generators/aws_kms_principals.py.
locals {
  central_logs_key_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid       = "EnableRoot"
        Effect    = "Allow"
        Principal = { AWS = "arn:aws:iam::PLACEHOLDER_ACCOUNT_ID_LogArchive:root" }
        Action    = "kms:*"
        Resource  = "*"
      },      {
        Sid       = "AllowCloudtrail"
        Effect    = "Allow"
        Principal = { Service = "cloudtrail.amazonaws.com" }
        Action    = ["kms:GenerateDataKey*", "kms:DescribeKey"]
        Resource  = "*"        # Confused-deputy guard — scope this service to resources we own.
        Condition = { "StringLike" = { "aws:SourceArn" = ["arn:aws:cloudtrail:*:PLACEHOLDER_ACCOUNT_ID_Management:trail/*", "arn:aws:cloudtrail:*:PLACEHOLDER_ACCOUNT_ID_LogArchive:trail/*"], "kms:EncryptionContext:aws:cloudtrail:arn" = ["arn:aws:cloudtrail:*:PLACEHOLDER_ACCOUNT_ID_Management:trail/*", "arn:aws:cloudtrail:*:PLACEHOLDER_ACCOUNT_ID_LogArchive:trail/*"] } }      },      {
        Sid       = "AllowConfig"
        Effect    = "Allow"
        Principal = { Service = "config.amazonaws.com" }
        Action    = ["kms:GenerateDataKey*", "kms:Decrypt", "kms:DescribeKey"]
        Resource  = "*"        # Confused-deputy guard — scope this service to resources we own.
        Condition = { "StringEquals" = { "aws:SourceOrgID" = "PLACEHOLDER_ORG_ID" } }      },      {
        Sid       = "AllowDeliverylogs"
        Effect    = "Allow"
        Principal = { Service = "delivery.logs.amazonaws.com" }
        Action    = ["kms:GenerateDataKey*", "kms:Decrypt", "kms:DescribeKey"]
        Resource  = "*"        # Confused-deputy guard — scope this service to resources we own.
        Condition = { "StringEquals" = { "aws:SourceOrgID" = "PLACEHOLDER_ORG_ID" } }      },      {
        Sid       = "AllowS3"
        Effect    = "Allow"
        Principal = { Service = "s3.amazonaws.com" }
        Action    = ["kms:GenerateDataKey*", "kms:Decrypt", "kms:DescribeKey"]
        Resource  = "*"        # Confused-deputy guard — scope this service to resources we own.
        Condition = { "StringEquals" = { "aws:SourceAccount" = "PLACEHOLDER_ACCOUNT_ID_LogArchive" } }      },    ]
  })
}

# Central-logs key (CloudTrail, Config, S3 log archive use this). Multi-region
# when the log archive bucket is replicated, so a same-alias key exists in the
# DR region for the replicated (SSE-KMS) objects.
resource "aws_kms_key" "central_logs" {
  provider                 = aws.log_archive
  description              = "CMK for the central log archive bucket and org CloudTrail"
  customer_master_key_spec = "SYMMETRIC_DEFAULT"
  key_usage                = "ENCRYPT_DECRYPT"
  enable_key_rotation      = true
  rotation_period_in_days  = 90
  deletion_window_in_days  = 30
  is_enabled               = true
  multi_region             = false

  policy = local.central_logs_key_policy

  tags = merge(local.default_tags, { Name = "central-logs-key" })
}

resource "aws_kms_alias" "central_logs" {
  provider      = aws.log_archive
  name          = "alias/acmecorp/central-logs-key"
  target_key_id = aws_kms_key.central_logs.key_id
}

# Optional: workload CMKs from values.cmks
resource "aws_kms_key" "workload_default" {
  description              = "Default workload CMK"
  customer_master_key_spec = "SYMMETRIC_DEFAULT"
  key_usage                = "ENCRYPT_DECRYPT"
  enable_key_rotation      = true
  # Cap to the rotation floor so an explicit per-key period can't exceed it.
  rotation_period_in_days  = 90
  deletion_window_in_days  = 30
  is_enabled               = true
  multi_region             = false

  # Explicit key policy (CKV2_AWS_64). Same default policy as the accelerator
  # key: account root admin + CloudWatch Logs use scoped to this account's
  # log groups (confused-deputy guard).
  policy = data.aws_iam_policy_document.kms_default.json

  tags = merge(local.default_tags, { Name = "workload-default" })
}

resource "aws_kms_alias" "workload_default" {
  name          = "alias/workload/default"
  target_key_id = aws_kms_key.workload_default.key_id
}
