# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# -----------------------------------------------------------------------------
# Generated by Merlin Studio v2 (architex-v2) — OpenTofu network_firewall.tf — centralized egress inspection
# Organization: AcmeCorp
# Profile:      STANDARD
# Generated:    2026-08-04T14:55:24.584722Z
# Wizard:       v1.0.0
# -----------------------------------------------------------------------------
# Scaffolding — not a finished artifact. Merlin renders this from your
# declared intent (profile, frameworks, accounts, topology). Adapt it to
# your environment: tighten CIDRs, refine policy bodies, add team tags,
# pin module versions, layer account-specific overrides. Re-run the wizard
# when *intent* shifts; keep day-to-day customisation in your IaC fork
# (regen overwrites this directory).
# Replace PLACEHOLDER_ tokens with real values from your AWS Organization
# before `tofu apply` / `cdk deploy` / LZA pipeline run — see PLACEHOLDERS.md.

# Rendered only when the topology SoT marks centralized egress live
# (generators/aws_network_topology.py -> network_topology.centralized_egress).
# The AWS Network Firewall lives in the inspection VPC (Network account) and
# inspects spoke egress that the Transit Gateway routes in. Spoke -> TGW ->
# inspection -> firewall -> NAT -> IGW. The TGW route-domain wiring and the
# inspection VPC's per-AZ egress routing are rendered in transit_gateway.tf /
# vpc.tf (next step); this file is the firewall, its policy, and its logging.

# Firewall policy: AWS-managed strict-order stateful rule groups + drop/alert on
# established flows by default. Referenced by managed ARN (no rule authoring).
resource "aws_networkfirewall_firewall_policy" "inspection_nfw" {
  provider = aws.network
  name     = "inspection-nfw-policy"

  # CMK-encrypted policy body (CKV_AWS_346 / FedRAMP SC-28). Customer-managed
  # KMS so key rotation and access control follow the LZA's KMS posture.
  encryption_configuration {
    type   = "CUSTOMER_KMS"
    key_id = aws_kms_key.accelerator.arn
  }

  firewall_policy {
    stateless_default_actions          = ["aws:forward_to_sfe"]
    stateless_fragment_default_actions = ["aws:forward_to_sfe"]

    stateful_engine_options {
      rule_order = "STRICT_ORDER"
    }
    stateful_default_actions = ["aws:drop_established", "aws:alert_established"]
    stateful_rule_group_reference {
      resource_arn = "arn:aws:network-firewall:us-east-1:aws-managed:stateful-rulegroup/AWSManagedRulesBotNetCommandAndControlDomainsStrictOrder"
    }
    stateful_rule_group_reference {
      resource_arn = "arn:aws:network-firewall:us-east-1:aws-managed:stateful-rulegroup/AWSManagedRulesMalwareDomainsStrictOrder"
    }
    stateful_rule_group_reference {
      resource_arn = "arn:aws:network-firewall:us-east-1:aws-managed:stateful-rulegroup/AWSManagedRulesAbusedLegitMalwareDomainsStrictOrder"
    }
  }

  tags = local.default_tags
}

# Firewall endpoints, one per firewall subnet (one per AZ) in the inspection VPC.
# The VPC + firewall subnets are hand-rolled in inspection_vpc.tf (the shared vpc
# module can't give the per-AZ route tables appliance-mode inspection needs).
resource "aws_networkfirewall_firewall" "inspection_nfw" {
  provider            = aws.network
  name                = "inspection-nfw"
  firewall_policy_arn = aws_networkfirewall_firewall_policy.inspection_nfw.arn
  vpc_id              = aws_vpc.inspection.id

  # Accidental delete protection (CKV_AWS_344). The firewall is the egress
  # choke point — losing it via a stray `terraform destroy` opens an
  # uninspected path. Operator must lift this explicitly to tear down.
  delete_protection = true

  # CMK-encrypted firewall config + flow tables (CKV_AWS_345 / FedRAMP SC-28).
  encryption_configuration {
    type   = "CUSTOMER_KMS"
    key_id = aws_kms_key.accelerator.arn
  }

  dynamic "subnet_mapping" {
    for_each = aws_subnet.inspection_fw
    content {
      subnet_id = subnet_mapping.value.id
    }
  }

  tags = local.default_tags
}

# AZ -> firewall-endpoint-id map, consumed by the inspection VPC route tables
# (inspection_vpc.tf) so each AZ's traffic is steered to its own endpoint.
locals {
  inspection_fw_endpoints = {
    for s in aws_networkfirewall_firewall.inspection_nfw.firewall_status[0].sync_states :
    s.availability_zone => s.attachment[0].endpoint_id
  }
}

# Flow + alert logging to CloudWatch in the inspection account (no cross-account
# bucket policy needed). Subscriptions/exports to the central log archive can be
# layered on later.
resource "aws_cloudwatch_log_group" "inspection_nfw_flow" {
  provider          = aws.network
  name              = "/aws/network-firewall/inspection-nfw/flow"
  retention_in_days = 365
  # CMK-encrypted (CKV_AWS_158 / FedRAMP SC-28). Same accelerator key as the
  # firewall + VPC flow log groups in this account.
  kms_key_id        = aws_kms_key.accelerator.arn
  tags              = local.default_tags
}

resource "aws_cloudwatch_log_group" "inspection_nfw_alert" {
  provider          = aws.network
  name              = "/aws/network-firewall/inspection-nfw/alert"
  retention_in_days = 365
  kms_key_id        = aws_kms_key.accelerator.arn   # CKV_AWS_158
  tags              = local.default_tags
}

resource "aws_networkfirewall_logging_configuration" "inspection_nfw" {
  provider     = aws.network
  firewall_arn = aws_networkfirewall_firewall.inspection_nfw.arn

  logging_configuration {
    log_destination_config {
      log_destination      = { logGroup = aws_cloudwatch_log_group.inspection_nfw_flow.name }
      log_destination_type = "CloudWatchLogs"
      log_type             = "FLOW"
    }
    log_destination_config {
      log_destination      = { logGroup = aws_cloudwatch_log_group.inspection_nfw_alert.name }
      log_destination_type = "CloudWatchLogs"
      log_type             = "ALERT"
    }
  }
}

output "network_firewall_arn" {
  value = aws_networkfirewall_firewall.inspection_nfw.arn
}
