# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# -----------------------------------------------------------------------------
# Generated by Merlin Studio v2 (architex-v2) — OpenTofu organizations.tf — AWS Organizations + OU tree
# Organization: AcmeCorp
# Profile:      STANDARD
# Generated:    2026-08-04T14:55:24.584722Z
# Wizard:       v1.0.0
# -----------------------------------------------------------------------------
# Scaffolding — not a finished artifact. Merlin renders this from your
# declared intent (profile, frameworks, accounts, topology). Adapt it to
# your environment: tighten CIDRs, refine policy bodies, add team tags,
# pin module versions, layer account-specific overrides. Re-run the wizard
# when *intent* shifts; keep day-to-day customisation in your IaC fork
# (regen overwrites this directory).
# Replace PLACEHOLDER_ tokens with real values from your AWS Organization
# before `tofu apply` / `cdk deploy` / LZA pipeline run — see PLACEHOLDERS.md.

# Read existing org (must be enabled at the management account).
data "aws_organizations_organization" "this" {}

# OU tree — source of truth: generators/aws_ou_tree.py. Covers the profile
# baseline, custom OUs, and every OU an account is assigned to (incl. nested
# paths like Workloads/Prod/PHI), so account parent_id references in
# accounts.tf always resolve. The Suspended OU is always present so the
# Quarantine SCP attaches to something — no empty deploymentTargets.
resource "aws_organizations_organizational_unit" "security" {
  name      = "Security"
  parent_id = data.aws_organizations_organization.this.roots[0].id
}
resource "aws_organizations_organizational_unit" "workloads" {
  name      = "Workloads"
  parent_id = data.aws_organizations_organization.this.roots[0].id
}
resource "aws_organizations_organizational_unit" "suspended" {
  name      = "Suspended"
  parent_id = data.aws_organizations_organization.this.roots[0].id
}
resource "aws_organizations_organizational_unit" "infrastructure" {
  name      = "Infrastructure"
  parent_id = data.aws_organizations_organization.this.roots[0].id
}
resource "aws_organizations_organizational_unit" "workloads_dev" {
  name      = "Dev"
  parent_id = aws_organizations_organizational_unit.workloads.id
}
resource "aws_organizations_organizational_unit" "workloads_prod" {
  name      = "Prod"
  parent_id = aws_organizations_organizational_unit.workloads.id
}
resource "aws_organizations_organizational_unit" "workloads_staging" {
  name      = "Staging"
  parent_id = aws_organizations_organizational_unit.workloads.id
}
resource "aws_organizations_organizational_unit" "workloads_sandbox" {
  name      = "Sandbox"
  parent_id = aws_organizations_organizational_unit.workloads.id
}
resource "aws_organizations_organizational_unit" "workloads_prod_pci" {
  name      = "PCI"
  parent_id = aws_organizations_organizational_unit.workloads_prod.id
}

# Enable AWS service-access principals required by LZA-style guardrails.
resource "aws_organizations_organization" "service_access" {
  count = 0   # Intentionally disabled — Organizations is already enabled.
              # We use this as a no-op anchor for documentation only.
  feature_set                   = "ALL"
  # Principals sourced from aws_service_maps.AWS_ORG_SERVICE_ACCESS_PRINCIPALS so
  # this anchor and the README pre-deploy checklist list the same set.
  aws_service_access_principals = [
    "cloudtrail.amazonaws.com",
    "config.amazonaws.com",
    "controltower.amazonaws.com",
    "guardduty.amazonaws.com",
    "securityhub.amazonaws.com",
    "ram.amazonaws.com",
    "sso.amazonaws.com",
    "fms.amazonaws.com",
  ]
  enabled_policy_types = [
    "SERVICE_CONTROL_POLICY",
    "TAG_POLICY",
  ]
}

# Service Control Policies — set sourced from generators/aws_scp_policies.py so
# OpenTofu / LZA / CDK / tfvars enforce the same guardrails (Quarantine, deny
# disabling CloudTrail/Config/GuardDuty/Security Hub, sandbox cost guardrails,
# region restrictions). Attachment names use <policy>_<ou> (quarantine_suspended
# is relied on by the cross-format drift test).
resource "aws_organizations_policy" "quarantine" {
  name        = "Quarantine-Policy"
  description = "Deny all actions for newly created accounts until reviewed."
  type        = "SERVICE_CONTROL_POLICY"
  content     = jsonencode({ "Version" = "2012-10-17", "Statement" = [{ "Sid" = "DenyAllNewAccounts", "Effect" = "Deny", "Action" = "*", "Resource" = "*", "Condition" = { "ArnNotLikeIfExists" = { "aws:PrincipalArn" = ["arn:aws:iam::*:role/OrganizationAccountAccessRole", "arn:aws:iam::*:role/AWSControlTowerExecution"] } } }] })
}
resource "aws_organizations_policy_attachment" "quarantine_suspended" {
  policy_id = aws_organizations_policy.quarantine.id
  target_id = aws_organizations_organizational_unit.suspended.id
}
resource "aws_organizations_policy" "guardrails_security" {
  name        = "Guardrails-Security"
  description = "Deny disabling CloudTrail/Config/GuardDuty/Security Hub. Attached to Workloads + Infrastructure — every member account that must never turn off a security service. The Security OU is intentionally excluded: it holds the delegated administrator (Audit), which legitimately calls GuardDuty/Security Hub member-management APIs this policy denies. (Targeting only Security — or Root — would either leave workloads unprotected or break the delegated admin.)"
  type        = "SERVICE_CONTROL_POLICY"
  content     = jsonencode({ "Version" = "2012-10-17", "Statement" = [{ "Sid" = "DenyDisableCloudTrail", "Effect" = "Deny", "Action" = ["cloudtrail:StopLogging", "cloudtrail:DeleteTrail", "cloudtrail:PutEventSelectors", "cloudtrail:UpdateTrail"], "Resource" = "*" }, { "Sid" = "DenyDisableConfig", "Effect" = "Deny", "Action" = ["config:DeleteConfigurationRecorder", "config:StopConfigurationRecorder", "config:DeleteDeliveryChannel", "config:DeleteConfigRule", "config:DeleteOrganizationConfigRule"], "Resource" = "*" }, { "Sid" = "DenyDisableGuardDuty", "Effect" = "Deny", "Action" = ["guardduty:DeleteDetector", "guardduty:UpdateDetector", "guardduty:DisassociateFromMasterAccount", "guardduty:DisassociateMembers", "guardduty:DeleteMembers", "guardduty:StopMonitoringMembers"], "Resource" = "*" }, { "Sid" = "DenyDisableSecurityHub", "Effect" = "Deny", "Action" = ["securityhub:DisableSecurityHub", "securityhub:DisassociateFromAdministratorAccount", "securityhub:DeleteMembers", "securityhub:DisassociateMembers"], "Resource" = "*" }] })
}
resource "aws_organizations_policy_attachment" "guardrails_security_workloads" {
  policy_id = aws_organizations_policy.guardrails_security.id
  target_id = aws_organizations_organizational_unit.workloads.id
}
resource "aws_organizations_policy_attachment" "guardrails_security_infrastructure" {
  policy_id = aws_organizations_policy.guardrails_security.id
  target_id = aws_organizations_organizational_unit.infrastructure.id
}
resource "aws_organizations_policy" "guardrails_sandbox" {
  name        = "Guardrails-Sandbox"
  description = "Cost guardrails for sandbox accounts (deny large/accelerated instance types + long-term capacity purchases). Scoped to the Sandbox OU only so it never restricts production workloads."
  type        = "SERVICE_CONTROL_POLICY"
  content     = jsonencode({ "Version" = "2012-10-17", "Statement" = [{ "Sid" = "DenyLargeAndAcceleratedInstanceTypes", "Effect" = "Deny", "Action" = "ec2:RunInstances", "Resource" = "arn:aws:ec2:*:*:instance/*", "Condition" = { "ForAnyValue:StringLike" = { "ec2:InstanceType" = ["*.4xlarge", "*.8xlarge", "*.12xlarge", "*.16xlarge", "*.24xlarge", "*.32xlarge", "*.48xlarge", "*.metal", "p3.*", "p4.*", "p5.*", "g4.*", "g5.*", "g6.*", "x1.*", "x2.*", "z1d.*", "u-*"] } } }, { "Sid" = "DenyLongTermCapacityPurchases", "Effect" = "Deny", "Action" = ["ec2:PurchaseReservedInstancesOffering", "ec2:PurchaseHostReservation", "ec2:PurchaseCapacityBlock", "savingsplans:CreateSavingsPlan", "rds:PurchaseReservedDBInstancesOffering", "elasticache:PurchaseReservedCacheNodesOffering", "redshift:PurchaseReservedNodeOffering", "opensearch:PurchaseReservedInstanceOffering", "es:PurchaseReservedElasticsearchInstanceOffering"], "Resource" = "*" }] })
}
resource "aws_organizations_policy_attachment" "guardrails_sandbox_workloads_sandbox" {
  policy_id = aws_organizations_policy.guardrails_sandbox.id
  target_id = aws_organizations_organizational_unit.workloads_sandbox.id
}
resource "aws_organizations_policy" "protect_security_services" {
  name        = "Protect-Security-Services"
  description = "Deny disabling CloudTrail / Config / GuardDuty / Security Hub at any account in the org. NIS2 Art 21 risk-management; FedRAMP/NIST SI-4 + CA-7 monitoring integrity; HIPAA admin safeguards; PCI-DSS Req 10 audit-log protection."
  type        = "SERVICE_CONTROL_POLICY"
  content     = jsonencode({ "Version" = "2012-10-17", "Statement" = [{ "Sid" = "DenyDisableCloudTrail", "Effect" = "Deny", "Action" = ["cloudtrail:StopLogging", "cloudtrail:DeleteTrail", "cloudtrail:PutEventSelectors", "cloudtrail:UpdateTrail"], "Resource" = "*" }, { "Sid" = "DenyDisableConfig", "Effect" = "Deny", "Action" = ["config:DeleteConfigurationRecorder", "config:StopConfigurationRecorder", "config:DeleteDeliveryChannel", "config:DeleteConfigRule", "config:DeleteOrganizationConfigRule"], "Resource" = "*" }, { "Sid" = "DenyDisableGuardDuty", "Effect" = "Deny", "Action" = ["guardduty:DeleteDetector", "guardduty:UpdateDetector", "guardduty:DisassociateFromMasterAccount", "guardduty:DisassociateMembers", "guardduty:DeleteMembers", "guardduty:StopMonitoringMembers"], "Resource" = "*" }, { "Sid" = "DenyDisableSecurityHub", "Effect" = "Deny", "Action" = ["securityhub:DisableSecurityHub", "securityhub:DisassociateFromAdministratorAccount", "securityhub:DeleteMembers", "securityhub:DisassociateMembers"], "Resource" = "*" }] })
}
resource "aws_organizations_policy_attachment" "protect_security_services_root" {
  policy_id = aws_organizations_policy.protect_security_services.id
  target_id = data.aws_organizations_organization.this.roots[0].id
}
resource "aws_organizations_policy" "require_imdsv2" {
  name        = "Require-IMDSv2"
  description = "Deny launching EC2 instances without IMDSv2 (http_tokens=required) and deny weakening the metadata options afterwards. Prevention paired with the ec2-imdsv2-check Config rule's detection. CIS 5.4/5.6; NIST/FedRAMP AC-3 + SC-23; PCI-DSS Req 2; HIPAA technical safeguards."
  type        = "SERVICE_CONTROL_POLICY"
  content     = jsonencode({ "Version" = "2012-10-17", "Statement" = [{ "Sid" = "DenyRunInstancesWithoutImdsv2", "Effect" = "Deny", "Action" = "ec2:RunInstances", "Resource" = "arn:aws:ec2:*:*:instance/*", "Condition" = { "StringNotEquals" = { "ec2:MetadataHttpTokens" = "required" } } }, { "Sid" = "DenyDowngradingMetadataOptions", "Effect" = "Deny", "Action" = "ec2:ModifyInstanceMetadataOptions", "Resource" = "*", "Condition" = { "StringNotEquals" = { "ec2:MetadataHttpTokens" = "required" } } }] })
}
resource "aws_organizations_policy_attachment" "require_imdsv2_root" {
  policy_id = aws_organizations_policy.require_imdsv2.id
  target_id = data.aws_organizations_organization.this.roots[0].id
}
resource "aws_organizations_policy" "deny_root_access" {
  name        = "Deny-Root-Access"
  description = "Deny all actions by the account root user (CIS 1.7 / Control Tower 'disallow root' guardrail). Break-glass is preserved: the condition only matches the root principal, so IAM roles/users are unaffected (use a break-glass admin role), and SCPs never apply to the organization management account's root."
  type        = "SERVICE_CONTROL_POLICY"
  content     = jsonencode({ "Version" = "2012-10-17", "Statement" = [{ "Sid" = "DenyRootUserActions", "Effect" = "Deny", "Action" = "*", "Resource" = "*", "Condition" = { "StringLike" = { "aws:PrincipalArn" = "arn:aws:iam::*:root" } } }] })
}
resource "aws_organizations_policy_attachment" "deny_root_access_workloads" {
  policy_id = aws_organizations_policy.deny_root_access.id
  target_id = aws_organizations_organizational_unit.workloads.id
}
