# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# -----------------------------------------------------------------------------
# Generated by Merlin Studio v2 (architex-v2) — OpenTofu outputs.tf — exported values for downstream modules / stacks
# Organization: AcmeCorp
# Profile:      STANDARD
# Generated:    2026-08-04T14:55:24.584722Z
# Wizard:       v1.0.0
# -----------------------------------------------------------------------------
# Scaffolding — not a finished artifact. Merlin renders this from your
# declared intent (profile, frameworks, accounts, topology). Adapt it to
# your environment: tighten CIDRs, refine policy bodies, add team tags,
# pin module versions, layer account-specific overrides. Re-run the wizard
# when *intent* shifts; keep day-to-day customisation in your IaC fork
# (regen overwrites this directory).
# Replace PLACEHOLDER_ tokens with real values from your AWS Organization
# before `tofu apply` / `cdk deploy` / LZA pipeline run — see PLACEHOLDERS.md.

output "organization_id" {
  description = "AWS Organizations ID."
  value       = data.aws_organizations_organization.this.id
}

output "organization_root_id" {
  description = "AWS Organizations root ID."
  value       = data.aws_organizations_organization.this.roots[0].id
}

output "account_ids" {
  description = "Map of LZ-managed account names to AWS account IDs."
  value       = local.created_account_ids
}

output "kms_accelerator_key_arn" {
  description = "ARN of the accelerator-managed default CMK."
  value       = aws_kms_key.accelerator.arn
}

output "kms_central_logs_key_arn" {
  description = "ARN of the central-logs CMK."
  value       = aws_kms_key.central_logs.arn
}

output "central_logs_bucket" {
  description = "S3 bucket name for the central log archive."
  value       = aws_s3_bucket.central_logs.id
}

output "cloudtrail_arn" {
  description = "Organization CloudTrail ARN."
  value       = aws_cloudtrail.org.arn
}

output "transit_gateway_id_export" {
  description = "Re-export the TGW id for downstream stacks."
  value       = aws_ec2_transit_gateway.primary.id
}

output "vpc_ids" {
  description = "Map of VPC names to their IDs."
  value = {
    "hub" = module.vpc_hub.vpc_id
    "workloads" = module.vpc_workloads.vpc_id
    "inspection" = aws_vpc.inspection.id
    "pci-cde" = module.vpc_pci_cde.vpc_id
    "workloads-dev" = module.vpc_workloads_dev.vpc_id
    "workloads-stg" = module.vpc_workloads_stg.vpc_id
    "workloads-sbx" = module.vpc_workloads_sbx.vpc_id
  }
}