# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# -----------------------------------------------------------------------------
# Generated by Merlin Studio v2 (architex-v2) — OpenTofu providers.tf
# Organization: AcmeCorp
# Profile:      STANDARD
# Generated:    2026-08-04T14:55:24.584722Z
# Wizard:       v1.0.0
# -----------------------------------------------------------------------------
# Scaffolding — not a finished artifact. Merlin renders this from your
# declared intent (profile, frameworks, accounts, topology). Adapt it to
# your environment: tighten CIDRs, refine policy bodies, add team tags,
# pin module versions, layer account-specific overrides. Re-run the wizard
# when *intent* shifts; keep day-to-day customisation in your IaC fork
# (regen overwrites this directory).
# Replace PLACEHOLDER_ tokens with real values from your AWS Organization
# before `tofu apply` / `cdk deploy` / LZA pipeline run — see PLACEHOLDERS.md.

# Default provider: home region
provider "aws" {
  region = "us-east-1"

  default_tags {
    tags = local.default_tags
  }
}

locals {
  default_tags = {
    ManagedBy    = "Merlin-Studio-v2"
    Organization = "AcmeCorp"
    Profile      = "standard"
    Environment  = "multi_env"
    CostCenter   = "PLATFORM"
    # Owner is REQUIRED by the org tag policy (tag-policies/standard-tagging.json).
    Owner        = "Platform-Team"
    Compliance   = "cis,pci_dss,iso27001,soc2"
  }
}


provider "aws" {
  alias  = "appdev"
  region = "us-east-1"
  assume_role {
    role_arn     = "arn:aws:iam::PLACEHOLDER_ACCOUNT_ID_AppDev:role/OrganizationAccountAccessRole"
    session_name = "merlin-studio-appdev-us-east-1"
  }
  default_tags {
    tags = local.default_tags
  }
}
provider "aws" {
  alias  = "appprod"
  region = "us-east-1"
  assume_role {
    role_arn     = "arn:aws:iam::PLACEHOLDER_ACCOUNT_ID_AppProd:role/OrganizationAccountAccessRole"
    session_name = "merlin-studio-appprod-us-east-1"
  }
  default_tags {
    tags = local.default_tags
  }
}
provider "aws" {
  alias  = "appsandbox"
  region = "us-east-1"
  assume_role {
    role_arn     = "arn:aws:iam::PLACEHOLDER_ACCOUNT_ID_AppSandbox:role/OrganizationAccountAccessRole"
    session_name = "merlin-studio-appsandbox-us-east-1"
  }
  default_tags {
    tags = local.default_tags
  }
}
provider "aws" {
  alias  = "appstaging"
  region = "us-east-1"
  assume_role {
    role_arn     = "arn:aws:iam::PLACEHOLDER_ACCOUNT_ID_AppStaging:role/OrganizationAccountAccessRole"
    session_name = "merlin-studio-appstaging-us-east-1"
  }
  default_tags {
    tags = local.default_tags
  }
}
provider "aws" {
  alias  = "network"
  region = "us-east-1"
  assume_role {
    role_arn     = "arn:aws:iam::PLACEHOLDER_ACCOUNT_ID_Network:role/OrganizationAccountAccessRole"
    session_name = "merlin-studio-network-us-east-1"
  }
  default_tags {
    tags = local.default_tags
  }
}
provider "aws" {
  alias  = "pciworkload"
  region = "us-east-1"
  assume_role {
    role_arn     = "arn:aws:iam::PLACEHOLDER_ACCOUNT_ID_PciWorkload:role/OrganizationAccountAccessRole"
    session_name = "merlin-studio-pciworkload-us-east-1"
  }
  default_tags {
    tags = local.default_tags
  }
}

# Provider for log archive account (cross-account writes)
provider "aws" {
  alias  = "log_archive"
  region = "us-east-1"
  assume_role {
    role_arn     = "arn:aws:iam::PLACEHOLDER_ACCOUNT_ID_LogArchive:role/OrganizationAccountAccessRole"
    session_name = "merlin-studio-log-archive"
  }
  default_tags {
    tags = local.default_tags
  }
}

# Provider for audit / security tooling account
provider "aws" {
  alias  = "audit"
  region = "us-east-1"
  assume_role {
    role_arn     = "arn:aws:iam::PLACEHOLDER_ACCOUNT_ID_Audit:role/OrganizationAccountAccessRole"
    session_name = "merlin-studio-audit"
  }
  default_tags {
    tags = local.default_tags
  }
}