# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# -----------------------------------------------------------------------------
# Generated by Merlin Studio v2 (architex-v2) — OpenTofu security.tf — GuardDuty + Security Hub + Access Analyzer + Macie
# Organization: AcmeCorp
# Profile:      STANDARD
# Generated:    2026-08-04T14:55:24.584722Z
# Wizard:       v1.0.0
# -----------------------------------------------------------------------------
# Scaffolding — not a finished artifact. Merlin renders this from your
# declared intent (profile, frameworks, accounts, topology). Adapt it to
# your environment: tighten CIDRs, refine policy bodies, add team tags,
# pin module versions, layer account-specific overrides. Re-run the wizard
# when *intent* shifts; keep day-to-day customisation in your IaC fork
# (regen overwrites this directory).
# Replace PLACEHOLDER_ tokens with real values from your AWS Organization
# before `tofu apply` / `cdk deploy` / LZA pipeline run — see PLACEHOLDERS.md.
# Compliance frameworks declared on this spec:
#   - cis
#   - pci_dss
#   - iso27001
#   - soc2

# GuardDuty delegated admin
resource "aws_guardduty_organization_admin_account" "this" {
  admin_account_id = "PLACEHOLDER_ACCOUNT_ID_Audit"
}

resource "aws_guardduty_detector" "this" {
  provider                     = aws.audit
  enable                       = true
  finding_publishing_frequency = "FIFTEEN_MINUTES"
}

resource "aws_guardduty_detector_feature" "s3_data_events" {
  provider    = aws.audit
  detector_id = aws_guardduty_detector.this.id
  name        = "S3_DATA_EVENTS"
  status      = "ENABLED"
}
resource "aws_guardduty_detector_feature" "eks_audit_logs" {
  provider    = aws.audit
  detector_id = aws_guardduty_detector.this.id
  name        = "EKS_AUDIT_LOGS"
  status      = "ENABLED"
}
resource "aws_guardduty_detector_feature" "ebs_malware_protection" {
  provider    = aws.audit
  detector_id = aws_guardduty_detector.this.id
  name        = "EBS_MALWARE_PROTECTION"
  status      = "ENABLED"
}
resource "aws_guardduty_detector_feature" "rds_login_events" {
  provider    = aws.audit
  detector_id = aws_guardduty_detector.this.id
  name        = "RDS_LOGIN_EVENTS"
  status      = "ENABLED"
}

resource "aws_guardduty_organization_configuration" "this" {
  provider                         = aws.audit
  auto_enable_organization_members = "ALL"
  detector_id                      = aws_guardduty_detector.this.id
}

resource "aws_guardduty_organization_configuration_feature" "s3_data_events" {
  provider    = aws.audit
  detector_id = aws_guardduty_detector.this.id
  name        = "S3_DATA_EVENTS"
  auto_enable = "ALL"
  depends_on  = [aws_guardduty_organization_configuration.this]
}
resource "aws_guardduty_organization_configuration_feature" "eks_audit_logs" {
  provider    = aws.audit
  detector_id = aws_guardduty_detector.this.id
  name        = "EKS_AUDIT_LOGS"
  auto_enable = "ALL"
  depends_on  = [aws_guardduty_organization_configuration.this]
}
resource "aws_guardduty_organization_configuration_feature" "ebs_malware_protection" {
  provider    = aws.audit
  detector_id = aws_guardduty_detector.this.id
  name        = "EBS_MALWARE_PROTECTION"
  auto_enable = "ALL"
  depends_on  = [aws_guardduty_organization_configuration.this]
}
resource "aws_guardduty_organization_configuration_feature" "rds_login_events" {
  provider    = aws.audit
  detector_id = aws_guardduty_detector.this.id
  name        = "RDS_LOGIN_EVENTS"
  auto_enable = "ALL"
  depends_on  = [aws_guardduty_organization_configuration.this]
}

# Security Hub
resource "aws_securityhub_organization_admin_account" "this" {
  admin_account_id = "PLACEHOLDER_ACCOUNT_ID_Audit"
}

resource "aws_securityhub_account" "this" {
  provider = aws.audit
}

resource "aws_securityhub_organization_configuration" "this" {
  provider     = aws.audit
  auto_enable  = true
  depends_on   = [aws_securityhub_account.this]
}

resource "aws_securityhub_finding_aggregator" "this" {
  provider     = aws.audit
  linking_mode = "ALL_REGIONS"
  depends_on   = [aws_securityhub_account.this]
}

resource "aws_securityhub_standards_subscription" "aws_foundational_security_best_practices_v_1_0_0" {
  provider      = aws.audit
  standards_arn = "arn:aws:securityhub:us-east-1::standards/aws-foundational-security-best-practices/v/1.0.0"
  depends_on    = [aws_securityhub_account.this]
}
resource "aws_securityhub_standards_subscription" "cis_aws_foundations_benchmark_v_3_0_0" {
  provider      = aws.audit
  standards_arn = "arn:aws:securityhub:us-east-1::standards/cis-aws-foundations-benchmark/v/3.0.0"
  depends_on    = [aws_securityhub_account.this]
}
resource "aws_securityhub_standards_subscription" "pci_dss_v_4_0_1" {
  provider      = aws.audit
  standards_arn = "arn:aws:securityhub:us-east-1::standards/pci-dss/v/4.0.1"
  depends_on    = [aws_securityhub_account.this]
}

# IAM Access Analyzer (organization-level)
resource "aws_accessanalyzer_analyzer" "org" {
  provider      = aws.audit
  analyzer_name = "org-analyzer"
  type          = "ORGANIZATION"
}

# Macie (sensitive-data discovery)
resource "aws_macie2_organization_admin_account" "this" {
  admin_account_id = "PLACEHOLDER_ACCOUNT_ID_Audit"
}

resource "aws_macie2_account" "this" {
  provider                     = aws.audit
  finding_publishing_frequency = "FIFTEEN_MINUTES"
  status                       = "ENABLED"
}

# Amazon Inspector (continuous vulnerability scanning — ECR / EC2 / Lambda).
# Delegated to the Audit account (org admin), with org-wide auto-enable for new
# member accounts. PCI-DSS 11.3.1 / NIST RA-5.
resource "aws_inspector2_delegated_admin_account" "this" {
  account_id = "PLACEHOLDER_ACCOUNT_ID_Audit"
}

resource "aws_inspector2_organization_configuration" "this" {
  provider = aws.audit
  auto_enable {
    ec2    = true
    ecr    = true
    lambda = true
  }
  depends_on = [aws_inspector2_delegated_admin_account.this]
}

# Org-wide IAM password policy (CIS 1.5–1.11).
resource "aws_iam_account_password_policy" "this" {
  minimum_password_length        = 14
  require_lowercase_characters   = true
  require_uppercase_characters   = true
  require_numbers                = true
  require_symbols                = true
  allow_users_to_change_password = true
  max_password_age               = 90
  password_reuse_prevention      = 24
  hard_expiry                    = false
}

# Account-level S3 public-access block (defends against accidental
# public buckets even when bucket-level settings are wrong).
resource "aws_s3_account_public_access_block" "this" {
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# Default EBS volume encryption (CIS 2.2.1).
resource "aws_ebs_encryption_by_default" "this" {
  enabled = true
}

# Default-encrypt EBS with the customer-managed key (encryption_requirements=cmk).
resource "aws_ebs_default_kms_key" "this" {
  key_arn = aws_kms_alias.workload_default.target_key_arn
  depends_on = [aws_ebs_encryption_by_default.this]
}
